// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCswmfG52MyCbD8gAOJxE3gesv1uapEvf4',
    appId: '1:506507624320:web:e1c54f88e1e657a3e6cb65',
    messagingSenderId: '506507624320',
    projectId: 'employee-db-8bd74',
    authDomain: 'employee-db-8bd74.firebaseapp.com',
    databaseURL: 'https://employee-db-8bd74-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-8bd74.firebasestorage.app',
    measurementId: 'G-1FT1X615Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM0RVIm724EN-pqfv_AZe0zAweNEL0FfE',
    appId: '1:506507624320:android:5105fcd273f1d649e6cb65',
    messagingSenderId: '506507624320',
    projectId: 'employee-db-8bd74',
    databaseURL: 'https://employee-db-8bd74-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-8bd74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiqTjIXd9s80077BS9E-Xl_JQ09NFDJ00',
    appId: '1:506507624320:ios:7175f76562f3a13fe6cb65',
    messagingSenderId: '506507624320',
    projectId: 'employee-db-8bd74',
    databaseURL: 'https://employee-db-8bd74-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-8bd74.firebasestorage.app',
    iosBundleId: 'com.example.employeeClarissaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiqTjIXd9s80077BS9E-Xl_JQ09NFDJ00',
    appId: '1:506507624320:ios:7175f76562f3a13fe6cb65',
    messagingSenderId: '506507624320',
    projectId: 'employee-db-8bd74',
    databaseURL: 'https://employee-db-8bd74-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-8bd74.firebasestorage.app',
    iosBundleId: 'com.example.employeeClarissaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCswmfG52MyCbD8gAOJxE3gesv1uapEvf4',
    appId: '1:506507624320:web:151866d668fcf08ae6cb65',
    messagingSenderId: '506507624320',
    projectId: 'employee-db-8bd74',
    authDomain: 'employee-db-8bd74.firebaseapp.com',
    databaseURL: 'https://employee-db-8bd74-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-8bd74.firebasestorage.app',
    measurementId: 'G-YF4K7VDWJ3',
  );
}
